# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: 首页
  url: /
  icon: fa-home
- page: 前端
  url: /categories/前端/
  icon: fa-html5
# - page: 后端
#   url: /categories/后端/
#   icon:
# - page: 工具
#   url: /categories/工具/
#   icon:
- page: 时间轴
  url: /archives/
  icon: fa-clock-o

## favicon
favicon: /jiuns.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: '' # ./img/head-img.jpg
  url: 'javascript:'

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  # - archive
  - tagcloud
  # - friends
  # - stick


## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: true
  posts:
    title: true
    text: true
    content: true
    categories: false
    tags: false

## 网站公告设置
notification: |-
            <p>
              别人都在假装正经，我只好假装不正经。
            </p>

## 社交设置
social:
#  - name: Github
#    icon: git
#    href: //github.com/shenliyang
 - name: 邮箱
   icon: envelope-o
   href: mailto:mrjackie168@gmail.com
 - name: 联系QQ
   icon: qq
   href: https://link.zhihu.com/?target=http%3A//wpa.qq.com/msgrd%3Fv%3D3%26uin%3D2469332606&site=qq&menu=yes
#  - name: 微信
#    icon: weixin
#    href: /
#  - name: QQ群
#    icon: users
#    href: /
#  - name: RSS
#    icon: feed
#    href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - Hexo官网: https://hexo.io/zh-cn/


# 主题自定义个性化配置

## 网站宣传语
branding: 博一个春夏秋冬,换一生无怨无悔.

## 设置banner背景图片
banner:
    img: /img/background.jpg #http://snippet.shenliyang.com/img/banner.jpg #https://source.unsplash.com/random/1920x200

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="" target="_blank">Jiuns.com</a>

## 文章打赏
reward:
  alipay: ''
  wepay: '' #../img/reward-wepay.jpg
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

### gitment
gitment:
  enable: false
  owner:
  repo:
  client_id:
  client_secret:
  perPage: 10

### 来必力
livere:
  enable: false
  livere_uid: MTAyMC8zMzA1MS85NjEz

### 友言评论(服务不稳定)
uyan:
  enable: false
  uyan_id: 1966422

### Disqus评论
disqus:
  enable: false
  shortname: snippet
  count: false

### 畅言评论(需要ICP备案)
changyan:
  enable: false
  appid:
  conf:

## Valine评论
valine:
   enable: true
   appId: 8t2L355yW5gi158Hb6lywjgn-gzGzoHsz
   appKey: HzdnOByXLrn9pKWweXlmiGIc
   placeholder: 说点什么吧
   notify: false
   verify: false
   avatar: mm
   meta: nick,mail
   pageSize: 10

## 网站访客统计
visit_counter:
   site: true
   page: true

## 网站访问统计分析

### 网盟CNZZ统计
cnzz_analytics: 1263868967

### 百度统计
baidu_analytics:

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2018
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.1
